### ISSUE TITLE
difference to convex hull

### ISSUE THREAD

**Issue by thymaro** [ludovico85/Home-range-analysis-Miminum-Convex-Polygon-MCP-QGIS-#1]
I looked at the information in this repo and don't understand what the difference is to the QGIS tool "minimum bounding geometry" with the convex hull option. Can you explain the difference?

**Comment by ludovico85** [comment]
First of all, this is not a question related to the model. Basically, there is no difference between the two algorithms (please see the [official documentation](https://docs.qgis.org/3.28/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#convex-hull)
